apiVersion: v1
kind: Service
metadata:
  name: first-app
spec:
  selector:
    app: first-app
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: first-app
  template:
    metadata:
      labels:
        app: first-app
    spec:
      containers:
        - name: api-container
          image: localhost:5000/firstproject-api
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: PG_HOST
              value: pg-database
            # - name: TEST
            #   valueFrom:
            #     configMapKeyRef:
            #       key: key
            #       name: configmap_name
          # envFrom:
          #   - configMapRef:
          #       name: config_map_name
          resources:
            limits:
              cpu: 20m
              memory: 200M
